### ISSUE TITLE
Possible IP comparison issue due to multiple possible representations

### ISSUE THREAD

**Issue by karalabe** [hashicorp/go-sockaddr#4]
The code at https://github.com/hashicorp/go-sockaddr/blob/master/ipaddrs.go#L47 makes the assumption that IPv4 addresses are always stored in a 4 byte long byte slice and similarly a IPv6 address is stored as a 16 byte slice.

This assumption however does not hold, as the net.IP's state (https://golang.org/pkg/net/#IP):

> Note that in this documentation, referring to an IP address as an IPv4 address or an IPv6 address is a semantic property of the address, not just the length of the byte slice: a **16-byte slice can still be an IPv4 address.**

Due to this byte slice based comparisons of IP addresses may not be always as meaningful as the user might expect, and the same IPv4 with different internal representation my cause comparison mismatches, resulting in unforseen anomalies.

*Note, this issue report was not initiated by my use of this package and noticing a bug, rather by creating an extension proposal for `go vet` and that signalling the possible misuse in this library.*

Cheers :)

**Comment by sean-** [comment]
@karalabe Thank you for this PR, your `go vet` extension will be most welcome.  I am very aware of this particular problem and it is one of the primary things that I had to work around in this `go-sockaddr` library.  For instance, the IPv4 type internally uses a `uint32` instead of a `net.IP`.  Regrettably I didn't spend any time doing the `IPv6` data types as two `uint64`s and instead used `math/big`.  If there is a better way to ensure a `net.IP` contains an IPv4 address without being an IPv6 address encoded using an IPv6 transitional address, I'd be interested in learning.  Thank you!

https://github.com/hashicorp/go-sockaddr/blob/c403ce7245ed06f545550eb6b80e0f2b1bd7566f/ipv4addr.go#L45-L58
